#!/bin/bash
#
# Use this to merge pdfs in Windows or Linux
# Needs pdftk installed
# https://www.pdflabs.com/tools/pdftk-the-pdf-toolkit/
#
v=`for ((i = 2; i<= $#; i++)); do echo ${!i} | tr '\n' ' '; done`
#echo $v
pdftk $v output $1
